<h1 style="color:green">Multivariate Regression</h1>
<p>Multivariate Regression is a method used to measure the degree at which more than one independent variable (predictors) and more than one dependent variable (responses), are linearly related. The method is broadly used to predict the behavior of the response variables associated to changes in the predictor variables, once a desired degree of relation has been established.</p>
<h3>Why should we use multivariate regression?</h3>
<p>Multiple regression is an extension of simple linear regression. It is used when we want to predict the value of a variable based on the value of two or more other variables. The variable we want to predict is called the dependent variable (or sometimes, the outcome, target or criterion variable). The variables we are using to predict the value of the dependent variable are called the independent variables (or sometimes, the predictor, explanatory or regressor variables).</p>
<img src="https://live.staticflickr.com/65535/48572939587_5f3f0ece53_z.jpg" align="center">

In [1]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/zITIFTsivN8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<h2 style="color:orange">Functions to use:</h2>
<h3>Concatenation</h3>

One of the most important aspects of implementing in the multivariate regression is to concatenate the first feature to the second feature to store them both into a single variable that can be calculated as a single variable. So x and y will become as a single variable (X) and it will be tested and trained, by the functions of transform and fit, into the model whether if it was a linear or a polynomial regression. The concatenation function is included in the numpy package.

Example: 

x = [[21][43][2][6][1]]
y = [[9][30][21][42][12]]

X = np.C_(x,y)

X = [[21,9][43,30][2,21][6,42][1,12]]

<img src="https://live.staticflickr.com/65535/48572780491_35a50ba387.jpg">

<h3>Axes3D</h3>

To plot the graph into a 3d scale, you must scatter (x,y,z) then you must create a variable with the figuring function from the "toolskit" package.
<p style="color:blue">
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
    </p>

Use the "ax" variable to plot it as you want to plot a normal 2D graph, but add the prediction of both the x and y variables into the graph to produce the regression.

<p style="color:blue">
ax.plot3D(xx,yy,ols.predict(XX),'r--',lw=5)
</p>

Then set the label onto what you want to set it as

<p style="color:blue">
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
</p>

Afterwards, you have to plot it into a 3D plotting platform by the "Matplotlib" application. 
<p style="color:red">Type (%matplotlib) on the beginning of the code to be able to call the 3D scaler of the application.</p> 


<h1 align="center" style="background-color:yellow">Tasks</h1>

<h2 style="color:red">Task 1:</h2>
<p>There is a data-set built in the "sklearn" package that is called "diabetes" that has a full data on diabetes cases. Retrieve that data as a dataframe so you could see what u are dealing with, then do a polynomial regression by storing the first 40 rows of "age" column as (x), storing the first 40 rows of "bmi" (y), and storing the first 40 rows of "bp" (z). Do a linear regression to find this question.

</p>

Make sure to import "sklearn" to be able to retrieve this data-set:

<p style="color:purple">from sklearn.datasets import load_diabetes
    </p>
    
        
diabetes = load_diabetes()


data=pd.DataFrame(diabetes.data,columns=diabetes.feature_names)

In [2]:
%matplotlib notebook
from sklearn.datasets import load_diabetes
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

diabetes = load_diabetes()
data=pd.DataFrame(diabetes.data,columns=diabetes.feature_names)

x = data["age"][:40]
y = data["bmi"][:40]
z = data["bp"][:40]
X = np.c_[x,y]


xx=np.linspace(min(x),max(x),20)
yy=np.linspace(min(y),max(y),20)

XX=np.c_[xx,yy]

ols = LinearRegression().fit(X,z)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter3D(x,y,z)
ax.plot3D(xx,yy,ols.predict(XX),'r--',lw=5)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
ols.score(np.c_[x,y],z)



<IPython.core.display.Javascript object>

0.12124690321612784

<h2 style="color:red">Task 2:</h2>
<p>Now with the same data and axes from the task above, make a polynomial regression with a second degree and plot it.</p>

In [3]:
from sklearn.preprocessing import PolynomialFeatures 

poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X)
ols.fit(X_poly,z)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter3D(x,y,z)
ax.plot3D(xx,yy,ols.predict(poly.fit_transform(XX)),'r--',lw=5)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')




<IPython.core.display.Javascript object>

Text(0.5, 0, 'Z Label')

<h2 style="color:red">Task 3:</h2>

Use np.arange to get an array of numbers 0,25,50,75,100. Then use np.linspace to get the same values.

In [4]:
print(np.arange(0,101,25))
print(np.linspace(0,100,5))

[  0  25  50  75 100]
[  0.  25.  50.  75. 100.]


<h2 style="color:red">Task 4:</h2>
<p>
With the data and the axes used in task 2, do 2 linear regressions, one with the (x,z) and the other with the (y,z) and plot them together in the same figure.</p>

In [5]:
%matplotlib notebook
from sklearn.datasets import load_diabetes
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

diabetes = load_diabetes()
data=pd.DataFrame(diabetes.data,columns=diabetes.feature_names)

x = data["age"][:40].values.reshape(-1,1)
y = data["bmi"][:40].values.reshape(-1,1)
z = data["bp"][:40]
X = np.c_[x,y]


xx=np.linspace(min(x),max(x),20)
yy=np.linspace(min(y),max(y),20)


ols = LinearRegression().fit(x,z)
olp = LinearRegression().fit(y,z)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter3D(x,y,z)
ax.plot3D(xx,ols.predict(xx),'r',lw=5)
ax.plot3D(yy,olp.predict(yy),'g',lw=5)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

<IPython.core.display.Javascript object>

Text(0.5, 0, 'Z Label')

<h2 style="color:red">Task 5:</h2>

Now with the same data use (x) and (z) to get a polynomial regression with a degree of 3. Another polynomial regression for the (y) and (z) with the degree of 4.

In [6]:
%matplotlib notebook
from sklearn.datasets import load_diabetes
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures 

diabetes = load_diabetes()
data=pd.DataFrame(diabetes.data,columns=diabetes.feature_names)

x = data["age"][:40].values.reshape(-1,1)
y = data["bmi"][:40].values.reshape(-1,1)
z = data["bp"][:40]
X = np.c_[x,y]


xx=np.linspace(min(x),max(x),20)
yy=np.linspace(min(y),max(y),20)

poly = PolynomialFeatures(3)
x_poly = poly.fit_transform(x)
poly.fit(x_poly,z)

poly2 = PolynomialFeatures(4)
y_poly = poly2.fit_transform(y)
poly2.fit(y_poly,z)

ols = LinearRegression().fit(x_poly,z)
olp = LinearRegression().fit(y_poly,z)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter3D(x,y,z)
ax.plot3D(xx,ols.predict(poly.fit_transform(xx)),'r',lw=5)
ax.plot3D(yy,olp.predict(poly2.fit_transform(yy)),'g',lw=5)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

<IPython.core.display.Javascript object>

Text(0.5, 0, 'Z Label')

<h2 style="color:red">Task 6:</h2>

Using the Diabetes data-set, predict the  values of (z) while (x) starts from 0 to 0.5, adding up 0.1 at a point, and while (y) was 0 to 0.05, adding up 0.01 at a point as a linear regression.

In [8]:
xyP

array([[0.  , 0.  ],
       [0.1 , 0.01],
       [0.2 , 0.02],
       [0.3 , 0.03],
       [0.4 , 0.04]])

In [12]:
xP = np.arange(0,0.50,0.10)
yP = np.arange(0,0.05,0.01)
xyP = np.c_[xP,yP]
ols.predict(xP)
olp.predict(yP)

ValueError: ignored

<h2 style="color:red">Task 7:</h2>

There is a data-set in sklearn called "iris", import that data-set then store the first 40 rows of data from "sepal length (cm)" into (x), "sepal width (cm)" to (y), and "petal length (cm)" into (z). 

Since we are using the linspace or arange to find the plotting, we can find the mean of x then y and get the value in the middle of both of them. Now plot a linear regression on the first half of the data. 

In [0]:
from sklearn.preprocessing import PolynomialFeatures 
from sklearn.datasets import load_iris

iris = load_iris()
data=pd.DataFrame(iris.data,columns=iris.feature_names)

z = data["sepal length (cm)"][:40]
y = data["sepal width (cm)"][:40]
x = data["petal length (cm)"][:40]

X = np.c_[x,y]

xx=np.linspace(min(x),(min(x)+max(x))/2,20)
yy=np.linspace(min(y),(min(y)+max(y))/2,20)

XX=np.c_[xx,yy]

ols = LinearRegression().fit(X,z)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter3D(x,y,z)
ax.plot3D(xx,yy,ols.predict(XX),'r--',lw=5)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')



<h2 style="color:red">Task 8:</h2>

from the same data above, make a polynomial regression for the first half of the data and then a linear regression for the second half of the data. For the polynomial set the degree to 2.

In [0]:
from sklearn.preprocessing import PolynomialFeatures 
from sklearn.datasets import load_iris

iris = load_iris()
data=pd.DataFrame(iris.data,columns=iris.feature_names)

z = data["sepal length (cm)"][:40]
y = data["sepal width (cm)"][:40]
x = data["petal length (cm)"][:40]

X = np.c_[x,y]

xx=np.linspace((min(x)+max(x))/2,max(x),20)
yy=np.linspace((min(y)+max(y))/2,max(y),20)

XX=np.c_[xx,yy]

xx2=np.linspace(min(x),(min(x)+max(x))/2,20)
yy2=np.linspace(min(y),(min(y)+max(y))/2,20)

XX2=np.c_[xx,yy]

ols2 = LinearRegression().fit(X,z)

poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X)
ols2.fit(X_poly,z)

ols = LinearRegression().fit(X,z)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter3D(x,y,z)
ax.plot3D(xx2,yy2,ols2.predict(poly.fit_transform(XX2)),'r--',lw=5)
ax.plot3D(xx,yy,ols.predict(XX),'r--',lw=5)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

<h2 style="color:red">Task 9:</h2>

From the data-set above do the opposite, so first half must be a linear and the other is polynomial.

In [0]:
from sklearn.preprocessing import PolynomialFeatures 
from sklearn.datasets import load_iris

iris = load_iris()
data=pd.DataFrame(iris.data,columns=iris.feature_names)

z = data["sepal length (cm)"][:40]
y = data["sepal width (cm)"][:40]
x = data["petal length (cm)"][:40]

X = np.c_[x,y]

xx2=np.linspace((min(x)+max(x))/2,max(x),20)
yy2=np.linspace((min(y)+max(y))/2,max(y),20)
XX=np.c_[xx,yy]

xx=np.linspace(min(x),(min(x)+max(x))/2,20)
yy=np.linspace(min(y),(min(y)+max(y))/2,20)

XX2=np.c_[xx,yy]

ols2 = LinearRegression().fit(X,z)

poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X)
ols2.fit(X_poly,z)

ols = LinearRegression().fit(X,z)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')


ax.scatter3D(x,y,z)
ax.plot3D(xx2,yy2,ols2.predict(poly.fit_transform(XX2)),'r--',lw=5)
ax.plot3D(xx,yy,ols.predict(XX),'r--',lw=5)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

<h1 style="background-color:red" align="center">Surface plotting</h1>

<img src="https://www.mathworks.com/help/examples/graphics/win64/ModifySurfacePlotAppearanceExample_01.png">

Surface plots are diagrams of three-dimensional data. Rather than showing the individual data points, surface plots show a functional relationship between a designated dependent variable (Y), and two independent variables (X and Z). The plot is a companion plot to the contour plot.

<h3 style="color:orange">Functions:</h3>

<h4>Meshgrid</h4>

Description. [X,Y] = meshgrid(x,y) transforms the domain specified by vectors x and y into arrays X and Y , which can be used to evaluate functions of two variables and three-dimensional mesh/surface plots.

<h4>Plot_surface</h4>

plot_surface is able to plot a grid (with z values) in 3D space based on x, y coordinates. The arrays of x and y are those created by numpy.meshgrid.

<h4>cmap:</h4>

cmap allows us to change the color of the surface plotting by adding it in the parameters of the plot_surface function. The sequential colors is one of the set of colors that can be used for it. 

            'Greys', 'Purples', 'Blues', 'Greens', 'Oranges', 'Reds',
            'YlOrBr', 'YlOrRd', 'OrRd', 'PuRd', 'RdPu', 'BuPu',
            'GnBu', 'PuBu', 'YlGnBu', 'PuBuGn', 'BuGn', 'YlGn'
            
Example: ax.plot_surface(x, y, Z, cmap=cm.Greys)

<h4 style="color:green">Calculations:</h4>

You need to find the R^2 of the formula by simply writing the (R = np.sqrt(x**2 + y**2)) formula then the (z) could simply be (Z = np.sin(R))

<h2 style="color:red">Task 10:</h2>

With the data below, do a surface plotting with them and let the Z be based on the formula given also below, use the PuBu of the "cm" package in matplotlib to change the color:

x = np.array([1,2,3,4,5,6])

y = np.array([6,5,4,3,2,1])


Make sure to import the "cm" package for the colors:

<p style="color:purple">from matplotlib import cm

In [0]:
from matplotlib import cm

x = np.array([1,2,3,4,5,6])
y = np.array([6,5,4,3,2,1])


fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

x,y = np.meshgrid(x,y)
R = np.sqrt(x**2 + y**2)
Z = np.sin(R)

surf = ax.plot_surface(x, y, Z, cmap=cm.PuBu)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')